# Generated by Django 2.0.4 on 2018-07-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.FloatField(help_text='CPU负载', max_length=64)),
                ('count_cpu', models.IntegerField(help_text='CPU 个数')),
                ('total_mem', models.FloatField(help_text='总内存', max_length=64)),
                ('total_disk', models.FloatField(help_text='总磁盘', max_length=64)),
                ('available_disk', models.FloatField(help_text='可用磁盘', max_length=64)),
                ('available_mem', models.FloatField(help_text='可用内存', max_length=64)),
                ('get_time', models.DateTimeField(auto_now_add=True, help_text='时间')),
            ],
            options={
                'db_table': 'monitorinfo',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='sever所在的位置', max_length=50)),
                ('IP', models.CharField(max_length=100)),
                ('env', models.CharField(help_text='环境', max_length=50)),
                ('job', models.CharField(help_text='所在的工作组', max_length=50)),
                ('server_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.Node')),
            ],
            options={
                'db_table': 'nodeinfo',
            },
        ),
        migrations.AddField(
            model_name='monitorinfo',
            name='server_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Node'),
        ),
    ]
